[package]
name = "indomitus"
version = "0.4.9"
authors = [ "Michael Bobrowski" ]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.4"
